#!/usr/bin/env bash

set -euo pipefail

TSX_PATH_ABSOLUTE="${PWD}/${TSX_PATH}"
PLAYWRIGHT_BROWSERS_PATH="${BUILD_WORKSPACE_DIRECTORY}/.playwright"

cd "${BUILD_WORKSPACE_DIRECTORY}/${BACKEND_PATH}"
export PLAYWRIGHT_BROWSERS_PATH

${TSX_PATH_ABSOLUTE} --watch "${BUILD_WORKSPACE_DIRECTORY}/${BACKEND_ENTRY_POINT}"
