package hmpb

var StringCatalog = map[string]string{
	"hmpb10WillBeElected":           "10 will be elected",
	"hmpb2WillBeElected":            "2 will be elected",
	"hmpb3WillBeElected":            "3 will be elected",
	"hmpb4WillBeElected":            "4 will be elected",
	"hmpb5WillBeElected":            "5 will be elected",
	"hmpb6WillBeElected":            "6 will be elected",
	"hmpb7WillBeElected":            "7 will be elected",
	"hmpb8WillBeElected":            "8 will be elected",
	"hmpb9WillBeElected":            "9 will be elected",
	"hmpbContinueVotingOnBack":      "Turn ballot over and continue voting",
	"hmpbContinueVotingOnNextSheet": "Continue voting on next ballot sheet",
	"hmpbInstructions":              "Instructions",
	"hmpbInstructionsToVoteText":    "To vote, completely fill in the oval next to your choice.",
	"hmpbInstructionsToVoteTitle":   "To Vote:",
	"hmpbInstructionsWriteInText":   "To vote for a person whose name is not on the ballot, write the person’s name on the \"Write-in\" line and completely fill in the oval next to the line.",
	"hmpbInstructionsWriteInTitle":  "To Vote for a Write-in:",
	"hmpbOfficialAbsenteeBallot":    "Official Absentee Ballot",
	"hmpbOfficialBallot":            "Official Ballot",
	"hmpbOfficialProvisionalBallot": "Official Provisional Ballot",
	"hmpbPage":                      "Page",
	"hmpbPageIntentionallyBlank":    "This page intentionally left blank",
	"hmpbSampleAbsenteeBallot":      "Sample Absentee Ballot",
	"hmpbSampleBallot":              "Sample Ballot",
	"hmpbSampleProvisionalBallot":   "Sample Provisional Ballot",
	"hmpbTestAbsenteeBallot":        "Test Absentee Ballot",
	"hmpbTestBallot":                "Test Ballot",
	"hmpbTestProvisionalBallot":     "Test Provisional Ballot",
	"hmpbVoteFor1":                  "Vote for 1",
	"hmpbVoteFor10":                 "Vote for up to 10",
	"hmpbVoteFor11":                 "Vote for up to 11",
	"hmpbVoteFor12":                 "Vote for up to 12",
	"hmpbVoteFor2":                  "Vote for up to 2",
	"hmpbVoteFor3":                  "Vote for up to 3",
	"hmpbVoteFor4":                  "Vote for up to 4",
	"hmpbVoteFor5":                  "Vote for up to 5",
	"hmpbVoteFor6":                  "Vote for up to 6",
	"hmpbVoteFor7":                  "Vote for up to 7",
	"hmpbVoteFor8":                  "Vote for up to 8",
	"hmpbVoteFor9":                  "Vote for up to 9",
	"hmpbVoteForNotMoreThan1":       "Vote for not more than 1",
	"hmpbVotingComplete":            "You have completed voting.",
	"hmpbWriteIn":                   "Write-in",
}
