import path from 'node:path';
import { ElectionDefinition, type Election } from '@vx/libs/types/elections';
import { asElectionDefinition } from '../../util';
import { asText as batchResultsCsvAsText } from './csvFiles/batchResults.csv';
import { asText as finalResultsCsvAsText } from './csvFiles/finalResults.csv';
import { election } from './election.json';

import * as castVoteRecords from './castVoteRecords';
export * as electionJson from './election.json';

export const batchCsvData = batchResultsCsvAsText();
export const finalCsvData = finalResultsCsvAsText();

export const singlePrecinctElection: Election = {
  ...election,
  precincts: [election.precincts[0]],
  ballotStyles: election.ballotStyles.map((ballotStyle) => ({
    ...ballotStyle,
    precincts: [election.precincts[0].id],
  })),
};
export function asSinglePrecinctElectionDefinition(): ElectionDefinition {
  return asElectionDefinition(singlePrecinctElection);
}

export * as systemSettings from '../systemSettings.json';

// Generated by libs/fixture-generators script: pnpm generate-cvr-fixtures
export const castVoteRecordExport = {
  asDirectoryPath: () =>
    path.join(castVoteRecords.asDirectoryPath(), 'generated'),
} as const;
