#!/usr/bin/env node

// @ts-check

require('tsx/cjs');

require('./src/validate-monorepo/cli')
  .main({
    stdin: process.stdin,
    stdout: process.stdout,
    stderr: process.stderr,
  })
  .catch((error) => {
    console.error(error.stack);
    return 1;
  })
  .then((exitCode) => {
    process.exitCode = exitCode;
  });
