#!/usr/bin/env node

require('tsx/cjs');

require('../src/printer/cli')
  .main(process.argv)
  .then((code) => {
    process.exitCode = code;
  })
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
